In [1]:
import numpy as np

Завдання 3

Варіант №17:

Дано два нечіткі трапецієподібні інтервали:

$A_і$ = ($a_і$, $b_і$, $c_і$, $d_і$) = (4,6,8,11);

$C_j$ = ($a_j$, $b_j$, $c_j$, $d_j$) = (2,6,9,14);

Виконати над ними арифметичні дії:

In [2]:
Ai = np.array([4,6,8,11])
Cj = np.array([2,6,9,14])

ai, bi, ci, di = Ai
aj, bj, cj, dj = Cj

1. Обчислюємо суму:

In [3]:
np.add(Ai, Cj)

array([ 6, 12, 17, 25])

2. Обчислюємо різницю:

In [4]:
[ai - bj - dj + cj, bi - bj, ci - cj, di + bj - aj -cj]

[-7, 0, -1, 6]

3. Обчислюємо добуток:

In [5]:
[bi * aj - bi * bj + ai * bj, bi * bj, ci * cj, ci * dj - ci * cj + di * cj]

[0, 36, 72, 139]

4. Обчислюємо частку:

In [6]:
np.round([(bi * cj - bi * dj + ai * cj) / cj**2, bi / cj, ci / bj, (ci * bj - ci * aj + di * bj) / bj**2], 2)

array([0.07, 0.67, 1.33, 2.72])

5. Обернені значення цих нечітких трапецієподібних інтервалів:

In [7]:
def inv(arr):
    a, b, c, d = arr
    return np.round([(2*c-d)/c**2, 1/c, 1/b, (2*b-a)/b**2], 2)

print(inv(Ai))
print(inv(Cj))

[0.08 0.12 0.17 0.22]
[0.05 0.11 0.17 0.28]
